version: '2'

volumes:
  settings:                          # Only required if using PERSISTENT flag (see below)

services:

  browser:
    build: .
    privileged: true # required for sound (/dev/snd) and V4L2 video-decode (/dev/video*) device access
    network_mode: host
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)